[workspace]
members = ["crates/*"]
default-members = [ "crates/kit" ]
resolver = "3"

[workspace.dependencies]
color-eyre = "0.6"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
tracing-error = { version = "0.2.0" }